language: python
sudo: false

python:
  - "2.7"

branches:
  only:
  - master

# command to install dependencies
install: 
  - pip install Sphinx

# command to run tests
script: 
  - sphinx-build -n -b html _build/doctrees . _build/html
# Flags used here, not in `make html`:
#  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
