= Reference Documentation
:numbered:
:icons: font
:experimental: y
:imagesdir: images/

:toc:

include::../_attributes.adoc[]

== Introduction

Goko is a multi-platform CNC control software. It provides the tools to move and execute jobs on your board, as well as modifying or editing GCode files.

=== Changelog

link:changelog.html[See changelog]

== Installation

The binary package is available here : https://bintray.com/goko/Goko/goko/_latestVersion

NOTE: a Java Runtime Environment (JRE 7 or above) is required. It can be downloaded from http://www.oracle.com/technetwork/java/javase/downloads/index.html

The installation itself is as easy as extracting a zip file to the folder of your choice.

Make sure you download the version matching your OS and your JVM instance.

WARNING: Both 32-bit and 64-bit Java Virtual Machine can be installed and used on the same computer

To check your installed java version, take the following steps:

 . Open a Windows Command Prompt
 . Type `java -version`
 . A 32 bit version will output something like :

  java version "x.x.x_xxx"
  Java(TM) SE Runtime Environment (build x.x.x_xxx)
  Java HotSpot(TM) Client VM (build xx.xx, mixed mode, sharing)

 . A 64 bit version will output the text below _(notice the 64-bit explicitely written)_

  java version "x.x.x_xxx" <br/>
  Java(TM) SE Runtime Environment (build x.x.x_xxx) <br/>
  Java HotSpot(TM) 64-Bit Server VM (build xx.xx, mixed mode)


include::firstSteps.adoc[]

include::connections.adoc[]

include::digitalreadout.adoc[]

include::shuttleexpress.adoc[]

include::gcode.adoc[]

include::macro.adoc[]
